---
apiVersion: v1
kind: pod
metadata:
  name: trail-3
spec:
  containers:
    - name: mysql
      image: mysql:8.3.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: jay
        - name: MYSQL_DATABASE
          value: student-id
        - name: MYSQL_USER
          value: jaya
        - name: MYSQL_PASSWORD
          value: jay
      resources:
        limits:
          cpu: 500m
          memory: 1Gi