---
apiVersion: v1 
kind: Pod
metadata:
  name: check-1
  labels:
    app: tommy
spec:
  containers:
    - name: tom
      image: tomcat:9-jdk17
      ports:
        - containerPort: 8080
      resources: 
        limits:
          cpu: 2g
          memory: 1Gi
      livenessProbe:
        httpGet:
          port: 8080
          path: /
