---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail-1
  labels:
    purpose: trying
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        env: dev
        version: v1
    spec:
      containers:
        - name: nginx1
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  ports:
    - name: svc1
      targetPort: 80
      port: 80
  selector:
    app: nginx