---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail-rs
  labels:
    name: trail-1
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: "1.0"
    spec:
      containers:
        - name: nginx1
          image: nginx
          