---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail-rs
  labels:
    use: trying
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        env: dev
        app: nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx1
          image: nginx
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: serv
spec:
  selector:
    app: nginx
  ports:
    - name: svc-port
      targetPort: 80
      port: 80
     