---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  labels:
    purpose: trying
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels:
      app: try
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      app: try
    spec:
      containers:
        - name: apache
          image: httpd
          args:
            - sleep
            - 1d
        - name: sidecar-1
          image: tomcat:11.0
          ports:
            - containerPort: 8080
          resources:
            cpu: 2000m
            memory: 2Gi
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          readinessProbe:
            httpGet:
              port: 8080
              path: /