---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class
  labels:
    purpose: trying
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels:
      app: try
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: try
    spec:
      containers:
        - name: apache
          image: httpd
          args:
            - sleep
            - 1d
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
          readinessProbe:
            httpGet:
              port: 80
              path: /
        - name: sidecar-1
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
          readinessProbe:
            httpGet:
              port: 80
              path: /