---
apiVersion: v1 
kind: Pod 
metadata:
  name: try
spec:
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
      env:
        - name: dev
          valueFrom:
            configMapKeyRef:
              key: key1
              name: confi
