---
apiVersion: v1 
kind: Pod
metadata:
  name: affintiy
  labels:
    app: myapp
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: myapp
          topologyKey: kubernetes.io/hostname
  containers:
    - name: affinity
      image: nginx
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"