--- 
apiVersion: v1 
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  containers:
    - name: tester
      image: httpd
      resources:
        limits:
          cpu: "1000m"
          memory: "1Gi"