---
apiVersion: v1 
kind: Pod 
metadata:
  name: db 
spec:
  containers:
    - name: sql
      image: mysql:8.0-oracle
      ports:
        - containerPort: 3306
      env:
        - name: user
          valueFrom:
            configMapKeyRef:
              key: user
              name: confi
        - name: password
          valueFrom:
            configMapKeyRef:
              key: password
              name: confi
        - name: database
          valueFrom:
            configMapKeyRef:
              key: database
              name: confi
        - name: rootpassword
          valueFrom:
            configMapKeyRef:
              key: rootpassword
      volumeMounts:
        - name: vol1
          mountPath: /mnt
  volumes:
    - name: vol1
      configMap: 
        name: confi
