---
apiVersion: v1 
kind: Pod
metadata:
  name: mysql 
spec:
  containers:
    - name: db
      image: mysql:8.0-debian
      ports:
        - containerPort: 3306
      resources:
        limits:
          cpu: "2Gi"
          memory: "1000m"
      volumeMounts:
        - name: db-1
          mountPath: /mnt
      env:
        - name: user
          valueFrom:
            configMapKeyRef:
              name: confi 
              key: user
        - name: password
          valueFrom:
            configMapKeyRef:
              name: confi 
              key: password
        - name: database
          valueFrom:
            configMapKeyRef:
              name: confi 
              key: database
        - name: rootpassword
          valueFrom:
            configMapKeyRef:
              name: confi 
              key: rootpassword
  volumes: 
    - name: db-1
      configMap:
        name: confi 
