---
apiVersion: v1
kind: Pod
metadata:
  name: prac-1
spec:
  initContainers:
    - name: dying-alpine
      image: alpine
      args:
        - sleep
        - 30s
  containers:
    - name: apache
      image: nginx
      resources:
        requests:
          cpu: 1000m
          memory: 1G
        limits:
          cpu: 1500m
          memory: 1.5G