apiVersion: v1
kind: Pod
metadata:
  name: prac-2
spec:
  initContainers:
    - name: init1
      image: alpine
      args:
        - sleep
        - 10s
    - name: init2
      image: alpine
      args:
        - sleep
        - 10s
    - name: init3
      image: alpine
      args:
        - sleep
        - 10s
  containers:
    - name: nginx1
      image: nginx
      resources:
        limits:
          cpu: 500m
          memory: 1G
    - name: sidecar1
      image: httpd
      args:
        - sleep
        - 1d
      resources:
        limits:
          cpu: 500m
          memory: 1G