---
apiVersion: v1
kind: Pod
metadata:
  name: prac-3
  labels:
    env: dev
    app: nginx
    version: 1.0
spec:
  containers:
    - name: nginx1
      image: nginx
      resources:
        limits:
          cpu: 500m
          memory: 1.5G