---
apiVersion: v1
kind: Pod 
metadata:
  name: non-tolerance
spec:
  containers:
    - name: prakash
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "128m"
          memory: "1Gi"
