---
apiVersion: v1
kind: Pod 
metadata:
  name: real 
  labels: 
    env: dev
spec:
  tolerations:
    - key: jay
      operator: Equal
      value: reddy
      effect: NoSchedule
  containers:
    - name: jay
      image: nginx
      ports:
        - containerPort: 80
