---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-2
  template:
    metadata:
      labels:
        app: check-2
    spec:
      containers:
        - name: check-2
          image: httpd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: check2-svc
spec:
  selector:
    app: check-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
