---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-page
  labels:
    app: blue 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: longflew/ingress:BLUEPAGE
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
