---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-1
  template:
    metadata:
      labels:
        app: check-1
    spec:
      containers:
        - name: check-1
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: check1-svc
spec:
  selector:
    app: check-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
