---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-page
  labels:
    app: yellow 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
        - name: yellow
          image: longflew/ingress:YELLOWPAGE
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: yellow-svc
spec:
  selector:
    app: yellow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
