---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dummy
  namespace: dev
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata: 
      labels:
        app: dummy-job
    spec: 
      activeDeadlineSeconds: 30
      template: 
        metadata:
          labels:
            app: dummy-job
        spec:
          restartPolicy: Never
          containers:
            - name: nginx
              image: nginx
              args:
                - sleep
                - 30s
            