---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: juju
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: apache-1
          image: httpd

