---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: svc-1
  labels:
    purpose: understanding
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
        env: dev
        version: "1.0"
    spec:
      containers:
        - name: spc-1
          image: jaypreddy/petclinic:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata:
  name: svc-1
spec:
  type: NodePort
  selector:
    app: spc
  ports:
    - name: svc-1
      targetPort: 8080
      port: 8080
      nodePort: 30000