---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail-1
  labels:
    purpose: trying
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        env: dev
        app: apache
        version: v1.0
    spec:
      containers:
        - name: nginx1
          image: httpd:2.4.58
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: apache
  ports:
    - name: svc-1
      targetPort: 80
      port: 80