---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jay-1
  labels:
    purpose: understanding
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: apache-1
  template:
    metadata:
      labels:
        app: apache-1
        env: dev
        version: v1.0
    spec:
      containers:
        - name: appi
          image: httpd
          ports:
            - containerPort: 80


---
apiVersion: v1 
kind: Service 
metadata:
  name: jayp
  labels:
    app: apache-1
spec:
  type: NodePort
  selector:
    app: apache-1
  ports:
    - name: jayp 
      port: 80
      targetPort: 80
      nodePort: 32000