---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding 
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: jay
  - apiGroup: "" 
    kind: ServiceAccount
    name: service 
