---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deploy-1
spec: 
  minReadySeconds: 5
  replicas: 6
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: trail-1
          image: nginx
          ports:
            - containerPort: 80