---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-based
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /blue(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: blue-svc
                port: 
                  number: 80
          - path: /green(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: green-svc
                port: 
                  number: 80
          - path: /yellow(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: yellow-svc
                port: 
                  number: 80
          - path: /red(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: red-svc
                port: 
                  number: 80
