---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: trail
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /nginx
            pathType: Prefix
            backend:
              service:
                name: check1-svc
                port: 
                  number: 80
          - path: /apache
            pathType: Prefix
            backend:
              service:
                name: check2-svc
                port: 
                  number: 80
              
              
