---
apiVersion: v1 
kind: Pod
metadata:
  name: node-s
  labels:
    app: dev
spec:
  nodeSelector:
    app: dev
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"