---
apiVersion: v1 
kind: Pod 
metadata:
  name: node-slay
  labels:
    env: dev
spec:
  nodeSelector: 
    env: dev
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 500m
          memory: 1G
