---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: check
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          args:
            - sleep
            - 1d

---
apiVersion: v1 
kind: Service
metadata:
  name: svc-1
spec:
  type: NodePort
  selector:
      app: test
  ports:
    - name: jay
      nodePort: 30001
      port: 80
      targetPort: 80


